[package]
name = "samplecli"
version = "0.1.0"
authors = ["naoya7076 <naoya7076@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
clap = "=3.0.0-beta.2"
futures = "0.3.6"
